"use client";

import { useEffect, useState } from "react";
import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { api } from "@/lib/api";

interface Report {
  claim: string;
  verdict: string;
  confidence: string;
  reasoning: string;
}

export default function ReportsPage() {

  const [reports, setReports] =
    useState<Report[]>([]);

  const [loading, setLoading] =
    useState(true);

  useEffect(() => {
    loadReports();
  }, []);

  async function loadReports() {

    try {

      const response =
        await api.get("/reports");

      setReports(
        response.data
      );

    } catch (error) {

      console.error(
        "Failed to load reports",
        error
      );

    } finally {

      setLoading(false);

    }
  }

  const trueCount =
    reports.filter(
      (r) =>
        r.verdict?.toLowerCase() ===
        "true"
    ).length;

  const falseCount =
    reports.filter(
      (r) =>
        r.verdict?.toLowerCase() ===
        "false"
    ).length;

  const misleadingCount =
    reports.filter(
      (r) =>
        r.verdict?.toLowerCase() ===
        "misleading"
    ).length;

  return (
    <DashboardLayout>

      <div className="space-y-8">

        <div>

          <h1 className="text-4xl font-bold">
            Verification Reports
          </h1>

          <p className="mt-2 text-zinc-400">
            View all verification
            results generated by
            TruthLens AI.
          </p>

        </div>

        {/* Stats */}

        <div className="grid grid-cols-1 gap-4 md:grid-cols-4">

          <div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5">

            <p className="text-zinc-500">
              Total Reports
            </p>

            <h2 className="mt-2 text-3xl font-bold">
              {reports.length}
            </h2>

          </div>

          <div className="rounded-2xl border border-green-900 bg-zinc-950 p-5">

            <p className="text-zinc-500">
              True
            </p>

            <h2 className="mt-2 text-3xl font-bold text-green-500">
              {trueCount}
            </h2>

          </div>

          <div className="rounded-2xl border border-red-900 bg-zinc-950 p-5">

            <p className="text-zinc-500">
              False
            </p>

            <h2 className="mt-2 text-3xl font-bold text-red-500">
              {falseCount}
            </h2>

          </div>

          <div className="rounded-2xl border border-yellow-900 bg-zinc-950 p-5">

            <p className="text-zinc-500">
              Misleading
            </p>

            <h2 className="mt-2 text-3xl font-bold text-yellow-500">
              {misleadingCount}
            </h2>

          </div>

        </div>

        {/* Reports */}

        {loading ? (

          <div className="rounded-2xl border border-zinc-800 p-8 text-center">
            Loading reports...
          </div>

        ) : (

          <div className="space-y-4">

            {reports.length === 0 ? (

              <div className="rounded-2xl border border-zinc-800 p-8 text-center text-zinc-500">
                No reports found.
              </div>

            ) : (

              reports.map(
                (
                  report,
                  index
                ) => (

                  <div
                    key={index}
                    className="
                      rounded-2xl
                      border
                      border-zinc-800
                      bg-zinc-950
                      p-6
                    "
                  >

                    <div className="flex items-center justify-between">

                      <h3 className="max-w-4xl text-lg font-semibold">
                        {report.claim}
                      </h3>

                      <span
                        className={`
                          rounded-full
                          px-3
                          py-1
                          text-sm
                          font-medium
                          ${
                            report.verdict?.toLowerCase() === "true"
                              ? "bg-green-500/10 text-green-500"
                              : report.verdict?.toLowerCase() === "false"
                              ? "bg-red-500/10 text-red-500"
                              : "bg-yellow-500/10 text-yellow-500"
                          }
                        `}
                      >
                        {report.verdict}
                      </span>

                    </div>

                    <p className="mt-3 text-sm text-zinc-400">
                      Confidence: {report.confidence}
                    </p>

                    <div className="mt-4 rounded-xl border border-zinc-800 bg-zinc-900/50 p-4">

                      <p className="text-sm text-zinc-300">
                        {report.reasoning}
                      </p>

                    </div>

                  </div>
                )
              )

            )}

          </div>

        )}

      </div>

    </DashboardLayout>
  );
}